/** Spot Sud Italia — con centri che noleggiano derive / catamarani sportivi. */
export const spots = [
  {
    id: "ischia-procida",
    name: "Ischia e Procida (Golfo di Napoli)",
    shortName: "Ischia e Procida",
    place: "Isole Flegree — Campania",
    region: "Campania",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Mare",
    wind: "Termiche pomeridiane del Golfo (8–14 nodi)",
    boats: "Laser, Tridente, piccoli catamarani",
    rental: "Scuole vela e charter isole Flegree",
    description:
      "Le isole flegree godono di ottime termiche. Presso le spiagge principali, o appoggiandosi a charter locali che offrono piccole derive, si naviga nel canale con panorama sul golfo. Ideale per primi bordi in mare caldo e stagione lunga.",
    lat: 40.73,
    lng: 13.9,
  },
  {
    id: "castellabate",
    name: "Castellabate / Cilento",
    shortName: "Cilento",
    place: "Porto San Marco di Castellabate — Campania",
    region: "Campania",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Mare",
    wind: "Brezze costiere moderate",
    boats: "Derive da turismo, scafi open leggeri",
    rental: "Servizi nautici area marina protetta del Cilento",
    description:
      "Una delle coste più intatte della regione. Ampie baie sabbiose facilitano uscite e rientri; attraverso i servizi nautici locali nell'area marina protetta si trovano piccole imbarcazioni a vela o uscite giornaliere verso Punta Licosa.",
    lat: 40.28,
    lng: 14.95,
  },
  {
    id: "posillipo",
    name: "Golfo di Napoli (Posillipo / Pozzuoli)",
    shortName: "Golfo di Napoli",
    place: "Posillipo e Pozzuoli — Campania",
    region: "Campania",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Mare",
    wind: "Termico da Sud-Ovest (10–14 nodi)",
    boats: "Derive classiche, Laser",
    rental: "Circoli storici di Napoli e basi del golfo",
    description:
      "Ottimo per derive classiche: il termico pomeridiano da Sud-Ovest permette di navigare con vista sul Vesuvio e Capri. Richiede già attenzione a traffico nautico e onde da scia tipiche del golfo.",
    lat: 40.81,
    lng: 14.21,
  },
  {
    id: "bari",
    name: "Bari e Costa Barese",
    shortName: "Bari",
    place: "Circolo Nautico Il Maestrale — Puglia",
    region: "Puglia",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Mare",
    wind: "Brezze adriatiche / Maestrale",
    boats: "Derive collettive, Laser",
    rental: "Circolo Nautico «Il Maestrale» (Bari)",
    description:
      "Base strutturata per iniziazione e perfezionamento su derive collettive e Laser, con uscite coordinate sulle acque adriatiche partendo da un porto attrezzato. Punto di accesso comodo per chi arriva in città.",
    lat: 41.12,
    lng: 16.87,
  },
  {
    id: "torre-guaceto",
    name: "Torre Guaceto (Brindisi)",
    shortName: "Torre Guaceto",
    place: "Riserva Marina — Carovigno / Brindisi",
    region: "Puglia",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Mare",
    wind: "Termico costante, mare spesso piatto",
    boats: "Laser Standard/Radial, RS Bahia, Hobie Cat 16",
    rental: "Sailing Center Torre Guaceto",
    description:
      "Perla del panorama nazionale: spirito comunitario e spartano, corsi e noleggio in riserva marina protetta. Acque cristalline, vento costante e varo da spiaggia — palestra marina che richiama lo spirito Caprera. Prenotare in anticipo in alta stagione.",
    lat: 40.715,
    lng: 17.8,
  },
  {
    id: "otranto",
    name: "Salento Adriatico (Otranto / San Foca)",
    shortName: "Salento Adriatico",
    place: "Otranto e San Foca — Puglia",
    region: "Puglia",
    level: "trans",
    levelLabel: "Medio-Avanzato",
    basin: "Mare",
    wind: "Maestrale e Tramontana tesi",
    boats: "Laser, catamarani, derive veloci",
    rental: "Circoli e centri del Salento",
    description:
      "Venti tesi di Maestrale e Tramontana con onda corta adriatica: richiede ottime doti di conduzione al timone. Spot che scala rapidamente da intermedio ad avanzato quando il vento sale.",
    lat: 40.15,
    lng: 18.49,
  },
  {
    id: "soverato",
    name: "Soverato (Golfo di Squillace)",
    shortName: "Soverato",
    place: "Costa degli Aranci — Calabria",
    region: "Calabria",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Mare",
    wind: "Termico pomeridiano ionico forte e costante",
    boats: "Laser, scafi collettivi, windsurf",
    rental: "Sailing the Gulf (Lega Navale Soverato)",
    description:
      "Lo Ionio calabrese regala termici pomeridiani che «puliscono» il cielo e creano planate su acqua relativamente piatta. Centro nautico con assistenza a terra per varo dalla spiaggia: flotta derive, collettivi e windsurf.",
    lat: 38.685,
    lng: 16.55,
  },
  {
    id: "stretto",
    name: "Stretto di Messina",
    shortName: "Stretto di Messina",
    place: "Reggio Calabria / Villa San Giovanni",
    region: "Calabria",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Mare",
    wind: "Venti incanalati + correnti ogni 6 ore",
    boats: "Derive tecniche / solo esperti",
    rental: "Basi locali (es. snodi a Villa San Giovanni) — logistica, non noleggio facile",
    description:
      "Spot per soli esperti: correnti fortissime che cambiano ogni sei ore e venti intensi incanalati nello Stretto. Palestra di marineria pura. Il noleggio «facile» di derive è raro; servono appoggi logistici e competenze elevate.",
    lat: 38.22,
    lng: 15.64,
  },
  {
    id: "isola-femmine",
    name: "Isola delle Femmine (Palermo)",
    shortName: "Isola delle Femmine",
    place: "Costa nord di Palermo — Sicilia",
    region: "Sicilia",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Mare",
    wind: "Venti del quadrante nord, spazi aperti",
    boats: "Laser, scafi collettivi / multipli",
    rental: "Isola del Vento (scuola FIV + noleggio)",
    description:
      "Uno degli spot migliori del Sud per il noleggio: scuola vela federale attiva che affitta imbarcazioni sportive di fronte all'isolotto protetto. Spazi aperti e venti del Nord; anche kayak e SUP in base.",
    lat: 38.2,
    lng: 13.24,
  },
  {
    id: "mondello",
    name: "Mondello / Palermo",
    shortName: "Mondello",
    place: "Circolo della Vela Sicilia — Palermo",
    region: "Sicilia",
    level: "trans",
    levelLabel: "Medio-Avanzato",
    basin: "Mare",
    wind: "Termici e brezze del golfo",
    boats: "Classi olimpiche, Laser, derive agonistiche",
    rental: "Circolo della Vela Sicilia (contatti / flotta sportiva)",
    description:
      "Culla della vela palermitana e club tra i più prestigiosi d'Italia. Orientato all'agonismo e alle classi olimpiche più che al noleggio turistico: ottimo hub per contatti e uscite tecniche nel capoluogo.",
    lat: 38.21,
    lng: 13.33,
  },
  {
    id: "marsala",
    name: "Marsala e Stagnone (Trapani)",
    shortName: "Marsala / Stagnone",
    place: "Laguna dello Stagnone e costa di Marsala",
    region: "Sicilia",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Mare",
    wind: "Vento costante (esterno laguna)",
    boats: "Catamarani, derive acrobatiche",
    rental: "Centri kitesurf/vela della costa di Marsala",
    description:
      "L'interno della laguna è regno del kitesurf per l'acqua bassa; le acque esterne di Marsala sono eccellenti per catamarani e derive acrobatiche grazie alla costanza del vento. Velocità e controllo in condizioni spesso tese.",
    lat: 37.8,
    lng: 12.43,
  },
];

export const regionMeta = {
  id: "sud",
  label: "Sud Italia",
  mapCenter: [39.2, 15.5],
  mapZoom: 6,
  note:
    "Al Sud il noleggio derive è legato a scuole e circoli: verifica disponibilità (spesso serve tessera FIV) e preparati al varo da spiaggia.",
};
