/** Spot di vela in deriva — coordinate approssimative dei punti di varo / aree tipiche. */
export const spots = [
  {
    id: "maggiore",
    name: "Sponda Est Lago Maggiore (Cerro/Luino)",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Lago",
    wind: "Inverna leggera (8–12 nodi)",
    boats: "Derive collettive, Tridente, RS Quest",
    lat: 45.908,
    lng: 8.62,
  },
  {
    id: "lecco",
    name: "Ramo di Lecco (Lago di Como)",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Lago",
    wind: "Breva leggera (8–10 nodi)",
    boats: "Tridente, RS Quest, Optimist",
    lat: 45.856,
    lng: 9.39,
  },
  {
    id: "iseo-orta",
    name: "Basso Lago d'Iseo e d'Orta",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Lago",
    wind: "Brezze termiche molto leggere",
    boats: "Optimist, Academy Dinghy",
    lat: 45.71,
    lng: 10.05,
  },
  {
    id: "desenzano",
    name: "Basso Lago di Garda (Desenzano)",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Lago",
    wind: "Brezza termica moderata",
    boats: "Optimist, Laser, 420",
    lat: 45.469,
    lng: 10.541,
  },
  {
    id: "dervio",
    name: "Alto Lago di Como (Dervio)",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Lago",
    wind: "Breva tesa (12–16 nodi)",
    boats: "RS Quest, Laser, 420",
    lat: 46.077,
    lng: 9.305,
  },
  {
    id: "brenzone",
    name: "Brenzone sul Garda",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Lago",
    wind: "Peler regolare mattutino",
    boats: "Laser, 420, RS Aero",
    lat: 45.707,
    lng: 10.765,
  },
  {
    id: "romagna",
    name: "Costa Romagnola (Cervia/Cesenatico)",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Mare",
    wind: "Termico estivo e onda corta",
    boats: "Laser, 470, Catamarani",
    lat: 44.246,
    lng: 12.352,
  },
  {
    id: "dongo",
    name: "Alto Lago di Como (Dongo)",
    level: "trans",
    levelLabel: "Medio-Avanzato",
    basin: "Lago",
    wind: "Breva forte e rafficata",
    boats: "Laser, Skiff (29er, Laser 4000)",
    lat: 46.122,
    lng: 9.281,
  },
  {
    id: "adriatico",
    name: "Alto Adriatico (Trieste/Grado)",
    level: "trans",
    levelLabel: "Medio-Avanzato",
    basin: "Mare",
    wind: "Brezze marine / Bora forte",
    boats: "Laser, 470, Scafi olimpici",
    lat: 45.677,
    lng: 13.395,
  },
  {
    id: "riva",
    name: "Alto Lago di Garda (Riva/Torbole)",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Lago",
    wind: "Peler e Ora forti (15–25 nodi)",
    boats: "29er/49er, Moth, Laser, Catamarani",
    lat: 45.876,
    lng: 10.872,
  },
  {
    id: "campione",
    name: "Campione del Garda",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Lago",
    wind: "Ora compressa sotto parete",
    boats: "Skiff, Catamarani, Waszp/Moth",
    lat: 45.808,
    lng: 10.748,
  },
  {
    id: "santacroce",
    name: "Lago di Santa Croce",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Lago",
    wind: "Termico canalizzato forte",
    boats: "Skiff, Contender, Windsurf",
    lat: 46.11,
    lng: 12.34,
  },
  {
    id: "sulzano",
    name: "Zona Centrale Lago d'Iseo (Sulzano)",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Lago",
    wind: "Montesina rafficata tra le isole",
    boats: "Derive performanti, Tattica",
    lat: 45.685,
    lng: 10.103,
  },
  {
    id: "liguria",
    name: "Riviera Ligure (Genova/Voltri/Sanremo)",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Mare",
    wind: "Tramontana / Scirocco con onda lunga",
    boats: "Derive oceaniche, marineria d'alto livello",
    lat: 44.426,
    lng: 8.75,
  },
];

export const LEVEL_COLORS = {
  base: "#1b7a4a",
  inter: "#b8860b",
  trans: "#c45c1a",
  adv: "#9b1c1c",
};
