/** Spot Nord Italia — coordinate approssimative dei punti di varo / aree tipiche. */
export const spots = [
  {
    id: "maggiore",
    name: "Sponda Est Lago Maggiore (Cerro/Luino)",
    shortName: "Lago Maggiore",
    place: "Sponda Lombarda — Cerro di Laveno / Ispra / Luino",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Lago",
    wind: "Inverna leggera (8–12 nodi)",
    boats: "Derive collettive, Tridente, RS Quest",
    rental: "Centro Vela Lago Maggiore (Laveno)",
    description:
      "La sponda orientale offre brezze termiche pomeridiane moderate (la Inverna) che raramente superano i 10–12 nodi. Scuole storiche come il Centro Vela Lago Maggiore a Laveno mettono a disposizione derive collettive (tipo Tridente o RS Quest) perfette per l'apprendimento in totale sicurezza senza l'incognita di onde formate.",
    lat: 45.908,
    lng: 8.62,
  },
  {
    id: "lecco",
    name: "Ramo di Lecco (Lago di Como)",
    shortName: "Lago di Como",
    place: "Ramo di Lecco / Valmadrera",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Lago",
    wind: "Breva leggera (8–10 nodi)",
    boats: "Tridente, RS Quest, Optimist",
    rental: "Circoli e scuole del ramo di Lecco",
    description:
      "Nelle prime ore del pomeriggio la Breva sale in modo graduale. Le acque protette del ramo di Lecco permettono ai principianti di fare pratica di assetto e conduzione senza subire la violenza delle raffiche dell'alto lago.",
    lat: 45.856,
    lng: 9.39,
  },
  {
    id: "iseo-orta",
    name: "Basso Lago d'Iseo e d'Orta",
    shortName: "Laghi Minori",
    place: "Lago d'Orta e Basso Lago d'Iseo",
    level: "base",
    levelLabel: "Base / Iniziazione",
    basin: "Lago",
    wind: "Brezze termiche molto leggere",
    boats: "Optimist, Academy Dinghy",
    rental: "Campus estivi e circoli locali",
    description:
      "Specchi d'acqua idilliaci con venti leggeri e costanti, isolati dalle grandi correnti alpine, ideali per i primi bordi assoluti in deriva o per i campus estivi dei ragazzi.",
    lat: 45.71,
    lng: 10.05,
  },
  {
    id: "desenzano",
    name: "Basso Lago di Garda (Desenzano)",
    shortName: "Lago di Garda — Basso/Medio",
    place: "Desenzano / Toscolano Maderno / Bardolino",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Lago",
    wind: "Brezza termica moderata",
    boats: "Optimist, Laser, 420",
    rental: "Circoli del basso e medio Garda",
    description:
      "Il basso lago offre ampi spazi di manovra e venti meno irruenti rispetto al nord, ma l'onda termica pomeridiana richiede già una buona coordinazione nei movimenti e sensibilità al timone per mantenere la barca in assetto.",
    lat: 45.469,
    lng: 10.541,
  },
  {
    id: "dervio",
    name: "Alto Lago di Como (Dervio)",
    shortName: "Lago di Como — Dervio",
    place: "Sponda Est — Dervio / Colico",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Lago",
    wind: "Breva tesa (12–16 nodi)",
    boats: "RS Quest, Laser, 420",
    rental: "Orza Scuola Vela (Dervio)",
    description:
      "Dervio è una vera e propria «palestra» della vela lombarda. Qui la Breva (vento da Sud) soffia nel pomeriggio con intensità decisa (spesso tra i 12 e i 16 nodi), incanalandosi tra le montagne. È lo spot ottimo per imparare l'uso del trapezio su derive performanti.",
    lat: 46.077,
    lng: 9.305,
  },
  {
    id: "brenzone",
    name: "Brenzone sul Garda",
    shortName: "Brenzone sul Garda",
    place: "Sponda Veneta",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Lago",
    wind: "Peler regolare mattutino",
    boats: "Laser, 420, RS Aero",
    rental: "Circolo Nautico Brenzone",
    description:
      "Situato in una posizione strategica, beneficia del Peler mattutino che qui arriva disteso e meno violento rispetto all'alto lago. Permette di allenarsi su derive tecniche (come il Laser o l'RS Aero) in condizioni di vento teso ma regolare.",
    lat: 45.707,
    lng: 10.765,
  },
  {
    id: "romagna",
    name: "Costa Romagnola (Cervia/Cesenatico)",
    shortName: "Costa Romagnola",
    place: "Cervia e Cesenatico",
    level: "inter",
    levelLabel: "Intermedio",
    basin: "Mare",
    wind: "Termico estivo e onda corta",
    boats: "Laser, 470, Catamarani",
    rental: "Circolo Vela Cesenatico / Congrega Velisti",
    description:
      "Rappresenta la perfetta palestra marina. Le lunghe spiagge sabbiose sono ideali per imparare le tecniche di varo e alaggio tra le onde. Il vento termico estivo è costante (8–14 nodi), ottimo per abituarsi all'onda corta dell'Adriatico e alla navigazione in mare aperto.",
    lat: 44.246,
    lng: 12.352,
  },
  {
    id: "dongo",
    name: "Alto Lago di Como (Dongo)",
    shortName: "Alto Lago di Como — Dongo",
    place: "Sponda Ovest — Dongo / Gravedona",
    level: "trans",
    levelLabel: "Medio-Avanzato",
    basin: "Lago",
    wind: "Breva forte e rafficata",
    boats: "Laser, Skiff (29er, Laser 4000)",
    rental: "Centro Formazione Vela Marvèlia",
    description:
      "Storica culla della didattica per derive veloci e Skiff acrobatici grazie alla base del Centro Formazione Vela Marvèlia. La Breva pomeridiana qui entra decisa e rafficata (12–18 nodi). L'ambiente stimolante e la presenza di scafi performanti (come i 29er) offrono un ponte perfetto verso la vela d'alta prestazione, richiamando lo spirito comunitario dei corsi avanzati di Caprera.",
    lat: 46.122,
    lng: 9.281,
  },
  {
    id: "adriatico",
    name: "Alto Adriatico (Trieste/Grado)",
    shortName: "Golfo di Trieste e Grado",
    place: "Trieste / Grado",
    level: "trans",
    levelLabel: "Medio-Avanzato",
    basin: "Mare",
    wind: "Brezze marine / Bora forte",
    boats: "Laser, 470, Scafi olimpici",
    rental: "Circoli dell'Alto Adriatico",
    description:
      "L'Alto Adriatico offre condizioni marine costiere eccellenti. Finché non soffia la Bora, le brezze di mare pomeridiane sono perfette per perfezionare la conduzione su onda salata, imparando a gestire anche le correnti marine.",
    lat: 45.677,
    lng: 13.395,
  },
  {
    id: "riva",
    name: "Alto Lago di Garda (Riva/Torbole)",
    shortName: "Alto Lago di Garda",
    place: "Malcesine / Torbole / Riva del Garda",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Lago",
    wind: "Peler e Ora forti (15–25 nodi)",
    boats: "29er/49er, Moth, Laser, Catamarani",
    rental: "Circoli alto Garda / scuole foil",
    description:
      "La capitale mondiale della vela d'acqua dolce. Le montagne stringono il lago a imbuto creando un effetto Venturi pazzesco. La mattina presto soffia il Peler da Nord (spesso sopra i 20 nodi) con onda formata; nel pomeriggio gira l'Ora da Sud (15–18 nodi costanti). È lo spot d'elezione per i moderni Moth foil e richiede una preparazione fisica eccellente.",
    lat: 45.876,
    lng: 10.872,
  },
  {
    id: "campione",
    name: "Campione del Garda",
    shortName: "Campione del Garda",
    place: "Sponda Bresciana",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Lago",
    wind: "Ora compressa sotto parete",
    boats: "Skiff, Catamarani, Waszp/Moth",
    rental: "Garda Optimist Academy / basi skiff",
    description:
      "Situato sotto una scogliera a picco, qui l'Ora subisce una fortissima compressione termica, picchiando durissimo sin dalle prime ore del pomeriggio. È un paradiso iper-tecnico per catamarani, skiff e discipline foiling (Waszp), dove i riflessi e il controllo del mezzo devono essere immediati.",
    lat: 45.808,
    lng: 10.748,
  },
  {
    id: "santacroce",
    name: "Lago di Santa Croce",
    shortName: "Lago di Santa Croce",
    place: "Belluno",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Lago",
    wind: "Termico canalizzato forte",
    boats: "Skiff, Contender, Windsurf",
    rental: "Circoli e basi del Nord-Est",
    description:
      "Un gioiello prealpino celeberrimo tra i regatanti. A causa della conformazione della sella di Fadalto, nel pomeriggio si attiva un vento termico fortissimo e teso che attira specialisti delle derive veloci da tutto il Nord-Est.",
    lat: 46.11,
    lng: 12.34,
  },
  {
    id: "sulzano",
    name: "Zona Centrale Lago d'Iseo (Sulzano)",
    shortName: "Zona Centrale Lago d'Iseo",
    place: "Sulzano / Monte Isola",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Lago",
    wind: "Montesina rafficata tra le isole",
    boats: "Derive performanti, Tattica",
    rental: "Associazione Nautica Sebina",
    description:
      "Attorno all'isola lacustre più alta d'Europa si generano corridoi di vento stretti e cambi di direzione repentini dovuti alle correnti termiche termofili (Montesina). Una palestra insostituibile per affinare la tattica di regata e la prontezza nelle manovre.",
    lat: 45.685,
    lng: 10.103,
  },
  {
    id: "liguria",
    name: "Riviera Ligure (Genova/Voltri/Sanremo)",
    shortName: "Riviera Ligure",
    place: "Genova / Voltri / Sanremo",
    level: "adv",
    levelLabel: "Avanzato",
    basin: "Mare",
    wind: "Tramontana / Scirocco con onda lunga",
    boats: "Derive oceaniche, marineria d'alto livello",
    rental: "Circoli della Riviera",
    description:
      "La Liguria d'inverno e in primavera regala giornate di Tramontana dura che scende dalle montagne o di Scirocco con onda lunga. Navigare in deriva qui richiede doti di marineria d'alto livello per gestire il mare formato e le uscite/rientri dalle scogliere.",
    lat: 44.426,
    lng: 8.75,
  },
];

export const regionMeta = {
  id: "nord",
  label: "Nord Italia",
  mapCenter: [45.6, 10.2],
  mapZoom: 7,
};
